lib/statWatch_web/router.ex
defmodule StatWatchWeb.Router do
  use StatWatchWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug StatWatch.Auth, repo: StatWatch.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StatWatchWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/profiles", ProfileController

    post "/login", SessionController, :create
    get "/login", SessionController, :new
    get "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", StatWatchWeb do
  #   pipe_through :api
  # end
end

lib/statWatch/accounts/user.ex
defmodule StatWatch.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset


  schema "users" do
    field :name, :string
    field :username, :string

    has_many :profiles, StatWatch.Core.Profile, on_delete: :delete_all
    has_one :credential, StatWatch.Accounts.Credential, on_delete: :delete_all
    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :username])
    |> validate_required([:name, :username])
    |> unique_constraint(:username)
  end
end

lib/statWatch_web/controllers/user_controller.ex
defmodule StatWatchWeb.UserController do
  use StatWatchWeb, :controller

  alias StatWatch.Accounts
  alias StatWatch.Accounts.User
  plug :logged_in_user when not action in [:new, :create]
  plug :correct_user when action in [:edit, :update, :delete]
  plug :authenticate_admin, [pokerface: true] when action in [:index]

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> StatWatch.Auth.login(user)
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user)) 

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: Routes.user_path(conn, :show, user))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: Routes.user_path(conn, :index))
  end

  defp correct_user(%{assigns: %{current_user: current, admin_user: admin}, 
                      params: %{"id" => id}} = conn, _params) do

    redirect_user = if current, do: Routes.user_path(conn, :show, current), else: "/"

    if String.to_integer(id) == current.id || admin do
      conn
    else
      conn
      |> put_flash(:error, "You do not have access to that page")
      |> redirect(to: Routes.user_path(conn, :show, current)) 
      |> halt() 
    end                  
  end
end

lib/statWatch_web/views/user_view.ex
defmodule StatWatchWeb.UserView do
  use StatWatchWeb, :view
end

lib/statWatch_web/templates/user/edit.html.eex
<h1>Edit User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/statWatch_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :username %>
  <%= text_input f, :username %>
  <%= error_tag f, :username %>

  <%= inputs_for f, :credential, fn cf ->%>
    <%= label cf, :email %>
    <%= text_input cf, :email %>
    <%= error_tag cf, :email %>

    <%= label cf, :password %>
    <%= password_input cf, :password %>
    <%= error_tag cf, :password %>

    <%= label cf, :password_confirmation %>
    <%= password_input cf, :password_confirmation %>
    <%= error_tag cf, :password_confirmation %>
  <% end %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/statWatch_web/templates/user/index.html.eex
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.username %></td>

      <td>
        <%= link "Show", to: Routes.user_path(@conn, :show, user) %>
        <%= link "Edit", to: Routes.user_path(@conn, :edit, user) %>
        <%= link "Delete", to: Routes.user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: Routes.user_path(@conn, :new) %></span>

lib/statWatch_web/templates/user/new.html.eex
<h1>New User</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.user_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.user_path(@conn, :index) %></span>

lib/statWatch_web/templates/user/show.html.eex
<% self = !!(@current_user && @current_user.id == @user.id) %>

<h1><%= @user.username%></h1>
<br/>
<strong>Name:</strong> <%= @user.name %>
<br/>
<strong>Email:</strong> <%= @user.credential.email%>
<br/>
<%= if @admin_user || self do %>
  <%= button "Create Profile", to: Routes.profile_path(@conn, :new),
      method: "get", class: "btn btn-primary", style: "margin-top: 1em;"%>
<% end %>
<hr/>

<%= if @admin_user || self do %>
<span><%= link "Edit", to: Routes.user_path(@conn, :edit, @user) %></span>
| <span><%= link "My Profiles", to: Routes.profile_path(@conn, :index) %></span>
<% end %>
<%= if @admin_user do %>
| <span><%= link "All Users", to: Routes.user_path(@conn, :index) %></span>
<% end %>