lib/statWatch_web/router.ex
defmodule StatWatchWeb.Router do
  use StatWatchWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug StatWatch.Auth, repo: StatWatch.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StatWatchWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/profiles", ProfileController

    post "/login", SessionController, :create
    get "/login", SessionController, :new
    get "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", StatWatchWeb do
  #   pipe_through :api
  # end
end

lib/statWatch_web/views/layout_view.ex
defmodule StatWatchWeb.LayoutView do
  use StatWatchWeb, :view
end

lib/statWatch_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>StatWatch</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul class = "nav nav-pills pull-right">
            <%= if @current_user do %>
              <li><%= link @current_user.username,
                  to: Routes.user_path(@conn, :show, @current_user)%>
              </li>

              <li>
                <%= link "Logout", to: Routes.session_path(@conn, :delete)%>
              </li>

            <% else %>  
              <li>
                <%= link "Login", to: Routes.session_path(@conn, :new)%>
              </li>
              <li>
                <%= link "Sign Up", to: Routes.user_path(@conn, :new)%>
              </li>  
            <% end %>
          </ul>
        </nav>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>